/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:3db5a887-e568-45da-9c66-de96e79f8775",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_glAfKR5z7",
    "aws_user_pools_web_client_id": "1shebij1r7l8qu1ps15dghjini",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wnm66kul6zbhdliyo2r7qd3fde.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
